# Generated by Django 4.2.16 on 2024-11-15 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simplepro.components.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', simplepro.components.fields.CharField(max_length=128, verbose_name='基础输入框')),
                ('f9', simplepro.components.fields.DateField(default=django.utils.timezone.now, verbose_name='Date日期选择')),
                ('f2', simplepro.components.fields.CharField(max_length=128, verbose_name='多行输入')),
                ('f3', simplepro.components.fields.CharField(max_length=128, verbose_name='密码')),
                ('f4', simplepro.components.fields.CharField(max_length=128, verbose_name='左边带图标')),
                ('f5', simplepro.components.fields.CharField(max_length=128, verbose_name='右边带图标')),
                ('f6', simplepro.components.fields.CharField(max_length=128, verbose_name='显示可输入长度')),
                ('f7', simplepro.components.fields.CharField(blank=True, max_length=128, null=True, verbose_name='复合输入框')),
                ('f8', simplepro.components.fields.CharField(blank=True, max_length=128, null=True, verbose_name='复合输入框')),
                ('creator', simplepro.components.fields.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'Char文本输入框',
                'verbose_name_plural': 'Char文本输入框',
            },
        ),
    ]
